# Generated by Django 5.2.5 on 2025-08-29 22:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('cutting', 'Illegal Cutting'), ('dumping', 'Pollution/Dumping'), ('reclamation', 'Land Reclamation'), ('other', 'Other Threat')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='report_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('validated', 'Validated'), ('action_taken', 'Action Taken'), ('resolved', 'Resolved'), ('false_report', 'False Report')], default='reported', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('official_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
